# Generated by Django 2.1.1 on 2020-09-28 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200926_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='BurnDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burn_docfile', models.FileField(upload_to='documents/burn/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='HandDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_docfile', models.FileField(upload_to='documents/hand/%Y/%m/%d')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 21, 23, 54, 819782), verbose_name='Created Date'),
        ),
    ]
