# Generated by Django 2.1.1 on 2020-09-28 14:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200928_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 22, 11, 40, 95128), verbose_name='Created Date'),
        ),
    ]
