# Generated by Django 2.1.1 on 2020-09-28 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200928_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 23, 4, 37, 955735), verbose_name='Created Date'),
        ),
    ]
