# Generated by Django 2.1.1 on 2020-09-28 15:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200928_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 23, 6, 29, 498006), verbose_name='Created Date'),
        ),
    ]
