# Generated by Django 2.2.4 on 2020-09-29 01:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200928_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 9, 49, 29, 712473), verbose_name='Created Date'),
        ),
    ]
