# Generated by Django 2.2.4 on 2020-09-29 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200929_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 9, 51, 13, 574767), verbose_name='Created Date'),
        ),
    ]
