# Generated by Django 2.2.10 on 2020-11-27 11:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('patient_id', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('sex', models.CharField(choices=[('f', 'Female'), ('m', 'Male'), ('u', 'Unsure')], max_length=1)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('burn_type', models.CharField(choices=[('s', 'Scald'), ('g', 'Grease'), ('n', 'Contact'), ('f', 'Flame'), ('c', 'Chemical'), ('e', 'Electric'), ('o', 'Other')], max_length=1)),
                ('comments', models.TextField()),
                ('created', models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 6, 34, 981267), verbose_name='Created Date')),
            ],
            options={
                'verbose_name_plural': 'PatientData',
            },
        ),
        migrations.CreateModel(
            name='PredictResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('result_code', models.CharField(blank=True, default='', max_length=1024)),
                ('predict_tbsa_ai', models.FloatField(default=0)),
                ('ai_after_eight_hours', models.FloatField(default=0)),
                ('ai_after_sixteen_hours', models.FloatField(default=0)),
                ('manual_after_eight_hours', models.FloatField(default=0)),
                ('manual_after_sixteen_hours', models.FloatField(default=0)),
                ('feedback_tbsa', models.FloatField(blank=True, default=0)),
                ('feedback_after_eight_hours', models.FloatField(blank=True, default=0)),
                ('feedback_after_sixteen_hours', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HandDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_docfile_resized', models.ImageField(blank=True, upload_to='documents/hand')),
                ('hand_docfile_ori', models.ImageField(blank=True, upload_to='documents/hand')),
                ('hand_predict_docfile', models.ImageField(blank=True, upload_to='documents/predict/hand')),
                ('file_location', models.CharField(default='', max_length=2048)),
                ('predicted', models.BooleanField(default=False)),
                ('process_predict', models.BooleanField(default=False)),
                ('hand_pixel', models.IntegerField(default=0)),
                ('hand_result', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.PredictResult')),
            ],
        ),
        migrations.CreateModel(
            name='BurnDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burn_docfile_resized', models.ImageField(blank=True, upload_to='documents/burn')),
                ('burn_docfile_ori', models.ImageField(blank=True, upload_to='documents/burn')),
                ('file_location', models.CharField(default='', max_length=2048)),
                ('burn_predict_docfile', models.ImageField(blank=True, upload_to='documents/predict/burn')),
                ('predicted', models.BooleanField(default=False)),
                ('process_predict', models.BooleanField(default=False)),
                ('burn_pixel', models.IntegerField(default=0)),
                ('user_calculated_tbsa', models.FloatField(blank=True, default=0.0, null=True)),
                ('burn_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.PredictResult')),
            ],
        ),
    ]
