# Generated by Django 2.2.10 on 2020-11-27 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 27, 19, 6, 42, 67418), verbose_name='Created Date'),
        ),
    ]
