# Generated by Django 2.2.10 on 2020-10-01 07:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burndocument',
            name='burn_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.PredictResult'),
        ),
        migrations.AlterField(
            model_name='handdocument',
            name='hand_result',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='demo.PredictResult'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 15, 31, 1, 47903), verbose_name='Created Date'),
        ),
    ]
