# Generated by Django 2.2.10 on 2020-10-03 11:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_auto_20201003_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 3, 19, 29, 58, 324711), verbose_name='Created Date'),
        ),
    ]
