# Generated by Django 2.2.10 on 2020-10-01 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20201001_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='burndocument',
            name='burn_docfile',
        ),
        migrations.RemoveField(
            model_name='handdocument',
            name='hand_docfile',
        ),
        migrations.AddField(
            model_name='burndocument',
            name='burn_docfile_ori',
            field=models.ImageField(blank=True, upload_to='documents/burn/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='burndocument',
            name='burn_docfile_resized',
            field=models.ImageField(blank=True, upload_to='documents/burn/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='handdocument',
            name='hand_docfile_ori',
            field=models.ImageField(blank=True, upload_to='documents/burn/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='handdocument',
            name='hand_docfile_resized',
            field=models.ImageField(blank=True, upload_to='documents/hand/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 16, 18, 47, 584294), verbose_name='Created Date'),
        ),
    ]
