# Generated by Django 2.2.10 on 2020-10-01 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_auto_20201001_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 22, 42, 43, 718938), verbose_name='Created Date'),
        ),
    ]
