# Generated by Django 2.2.10 on 2020-10-01 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_auto_20201001_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 1, 22, 52, 38, 20826), verbose_name='Created Date'),
        ),
    ]
