# Generated by Django 2.2.10 on 2020-10-02 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0008_auto_20201001_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='burndocument',
            name='burn_pixel',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='handdocument',
            name='hand_pixel',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 14, 31, 38, 573349), verbose_name='Created Date'),
        ),
    ]
