# Generated by Django 2.2.10 on 2020-10-02 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0009_auto_20201002_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burndocument',
            name='burn_docfile_ori',
            field=models.ImageField(blank=True, upload_to='documents/burn'),
        ),
        migrations.AlterField(
            model_name='burndocument',
            name='burn_docfile_resized',
            field=models.ImageField(blank=True, upload_to='documents/burn'),
        ),
        migrations.AlterField(
            model_name='burndocument',
            name='burn_predict_docfile',
            field=models.ImageField(blank=True, upload_to='documents/predict/burn'),
        ),
        migrations.AlterField(
            model_name='handdocument',
            name='hand_docfile_ori',
            field=models.ImageField(blank=True, upload_to='documents/hand'),
        ),
        migrations.AlterField(
            model_name='handdocument',
            name='hand_docfile_resized',
            field=models.ImageField(blank=True, upload_to='documents/hand'),
        ),
        migrations.AlterField(
            model_name='handdocument',
            name='hand_predict_docfile',
            field=models.ImageField(blank=True, upload_to='documents/predict/hand'),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 15, 51, 32, 399351), verbose_name='Created Date'),
        ),
    ]
