# Generated by Django 2.2.10 on 2020-10-02 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0010_auto_20201002_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictresult',
            name='result_code',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 21, 53, 29, 458702), verbose_name='Created Date'),
        ),
    ]
