# Generated by Django 2.2.10 on 2020-10-02 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0011_auto_20201002_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictresult',
            name='predict_tbsa',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 21, 55, 11, 941207), verbose_name='Created Date'),
        ),
    ]
