# Generated by Django 2.2.10 on 2020-10-03 04:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0013_auto_20201002_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 2, 21, 47, 30, 369536), verbose_name='Created Date'),
        ),
    ]
